name: TheDark
version: '${project.version}'
main: io.github.greatericontop.thedark.TheDark
api-version: 1.19


commands:
  thedark:
    description: TheDark Command
    usage: §c/thedark §6[§finfo, spawnBasicZombies, spawnDebugZombie, spawnSomeEnemies, spawnRandomAssault, spawnVindicator, addMe, setSign, giveGun, forceBuyGun, emerald, startRoundHere§6]
    permission: thedark.command
    permission-message: §cNo permission!

permissions:
  thedark.command:
    default: op