name: TheDark
version: '${project.version}'
main: io.github.greatericontop.thedark.TheDark
api-version: 1.19


commands:
  thedark:
    description: TheDark Command
    usage: §c/thedark §6[§finfo, spawnMob, addMe, addCoins, setSign, giveGun, buyGun, emerald, startRound, startRoundHere§6]
    permission: thedark.command
    permission-message: §cNo permission!

permissions:
  thedark.command:
    default: op