name: TheDark
version: '${project.version}'
main: io.github.greatericontop.thedark.TheDark
api-version: 1.19


commands:
  thedark:
    description: TheDark Command
    usage: §c/thedark [info, spawnBasicZombies, spawnDebugZombie, spawnSomeEnemies, addMe, setSign, makeGun, giveGun]
    permission: thedark.command
    permission-message: §cNo permission!

permissions:
  thedark.command:
    default: op